Improve
JMoVS/JUMP pull request #9
Opened 2021-08-12 10:12 UTC by SebastianRuffert

2021-08-23 12:08 UTC, JMoVS commented on MeasurementProgram.py
> +            #TODO One task is still missing, don't know what the input is
a bit unclear if this is still relevant?

2021-09-02 07:27 UTC, SebastianRuffert commented on MeasurementProgram.py
> +            #TODO One task is still missing, don't know what the input is
Yes kind of, since I do not yet know if this corresponds to the wished procedure. I just need to see the specific progress of starting a measurement again

2021-09-30 15:29 UTC, JMoVS requested changes

2021-09-30 15:29 UTC, JMoVS commented on MeasurementProgram.py
> +MP.start()
please don't remove the new line at the end of the file

2021-09-30 15:29 UTC, JMoVS commented on DataStorage.py
> +        #TODO
what is to do here?

2021-09-30 15:29 UTC, JMoVS commented on DataStorage.py
> +            indeces=0#Maybe 1 is correct, not sure
please remove comment

2021-09-30 16:30 UTC, JMoVS approved these changes

2021-09-30 16:37 UTC, JMoVS commented
thanks for the contribution!

2021-09-30 16:37 UTC, closed without merging